# Generated by Django 5.1.6 on 2025-03-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='isAdmin',
            new_name='is_blocked',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='isBlocked',
            new_name='is_staff',
        ),
    ]
